// FUN_14000cde0 @ 14000cde0

void FUN_14000cde0(void)

{
  QString::QString((QString *)&DAT_140cad340,"Bank Select MSB");
  QString::QString((QString *)&DAT_140cad358,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140cad370,"Breath Control MSB");
  QString::QString((QString *)&DAT_140cad388,"Undefined");
  QString::QString((QString *)&DAT_140cad3a0,"Foot Control MSB");
  QString::QString((QString *)&DAT_140cad3b8,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140cad3d0,"Data Entry MSB");
  QString::QString((QString *)&DAT_140cad3e8,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140cad400,"Balance MSB");
  QString::QString((QString *)&DAT_140cad418,"Undefined");
  QString::QString((QString *)&DAT_140cad430,"Pan MSB");
  QString::QString((QString *)&DAT_140cad448,"Expression MSB");
  QString::QString((QString *)&DAT_140cad460,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140cad478,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140cad490,"Undefined");
  QString::QString((QString *)&DAT_140cad4a8,"Undefined");
  QString::QString((QString *)&DAT_140cad4c0,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140cad4d8,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140cad4f0,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140cad508,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140cad520,"Undefined");
  QString::QString((QString *)&DAT_140cad538,"Undefined");
  QString::QString((QString *)&DAT_140cad550,"Undefined");
  QString::QString((QString *)&DAT_140cad568,"Undefined");
  QString::QString((QString *)&DAT_140cad580,"Undefined");
  QString::QString((QString *)&DAT_140cad598,"Undefined");
  QString::QString((QString *)&DAT_140cad5b0,"Undefined");
  QString::QString((QString *)&DAT_140cad5c8,"Undefined");
  QString::QString((QString *)&DAT_140cad5e0,"Undefined");
  QString::QString((QString *)&DAT_140cad5f8,"Undefined");
  QString::QString((QString *)&DAT_140cad610,"Undefined");
  QString::QString((QString *)&DAT_140cad628,"Undefined");
  QString::QString((QString *)&DAT_140cad640,"Bank Select LSB");
  QString::QString((QString *)&DAT_140cad658,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140cad670,"Breath Control LSB");
  QString::QString((QString *)&DAT_140cad688,"Undefined");
  QString::QString((QString *)&DAT_140cad6a0,"Foot Control LSB");
  QString::QString((QString *)&DAT_140cad6b8,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140cad6d0,"Data Entry LSB");
  QString::QString((QString *)&DAT_140cad6e8,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140cad700,"Balance LSB");
  QString::QString((QString *)&DAT_140cad718,"Undefined");
  QString::QString((QString *)&DAT_140cad730,"Pan LSB");
  QString::QString((QString *)&DAT_140cad748,"Expression LSB");
  QString::QString((QString *)&DAT_140cad760,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140cad778,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140cad790,"Undefined");
  QString::QString((QString *)&DAT_140cad7a8,"Undefined");
  QString::QString((QString *)&DAT_140cad7c0,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140cad7d8,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140cad7f0,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140cad808,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140cad820,"Undefined");
  QString::QString((QString *)&DAT_140cad838,"Undefined");
  QString::QString((QString *)&DAT_140cad850,"Undefined");
  QString::QString((QString *)&DAT_140cad868,"Undefined");
  QString::QString((QString *)&DAT_140cad880,"Undefined");
  QString::QString((QString *)&DAT_140cad898,"Undefined");
  QString::QString((QString *)&DAT_140cad8b0,"Undefined");
  QString::QString((QString *)&DAT_140cad8c8,"Undefined");
  QString::QString((QString *)&DAT_140cad8e0,"Undefined");
  QString::QString((QString *)&DAT_140cad8f8,"Undefined");
  QString::QString((QString *)&DAT_140cad910,"Undefined");
  QString::QString((QString *)&DAT_140cad928,"Undefined");
  QString::QString((QString *)&DAT_140cad940,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140cad958,"Portamento On/Off");
  QString::QString((QString *)&DAT_140cad970,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140cad988,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140cad9a0,"Legato Footswitch");
  QString::QString((QString *)&DAT_140cad9b8,"Hold 2");
  QString::QString((QString *)&DAT_140cad9d0,"Sound Variation");
  QString::QString((QString *)&DAT_140cad9e8,"Timbre");
  QString::QString((QString *)&DAT_140cada00,"Release Time");
  QString::QString((QString *)&DAT_140cada18,"Attack Time");
  QString::QString((QString *)&DAT_140cada30,"Brightness");
  QString::QString((QString *)&DAT_140cada48,"Decay Time");
  QString::QString((QString *)&DAT_140cada60,"Vibrato Rate");
  QString::QString((QString *)&DAT_140cada78,"Vibrato Depth");
  QString::QString((QString *)&DAT_140cada90,"Vibrato Delay");
  QString::QString((QString *)&DAT_140cadaa8,"Undefined");
  QString::QString((QString *)&DAT_140cadac0,"General Purpose 5");
  QString::QString((QString *)&DAT_140cadad8,"General Purpose 6");
  QString::QString((QString *)&DAT_140cadaf0,"General Purpose 7");
  QString::QString((QString *)&DAT_140cadb08,"General Purpose 8");
  QString::QString((QString *)&DAT_140cadb20,"Portamento Control");
  QString::QString((QString *)&DAT_140cadb38,"Undefined");
  QString::QString((QString *)&DAT_140cadb50,"Undefined");
  QString::QString((QString *)&DAT_140cadb68,"Undefined");
  QString::QString((QString *)&DAT_140cadb80,"High Res. Velocity");
  QString::QString((QString *)&DAT_140cadb98,"Undefined");
  QString::QString((QString *)&DAT_140cadbb0,"Undefined");
  QString::QString((QString *)&DAT_140cadbc8,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140cadbe0,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140cadbf8,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140cadc10,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140cadc28,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140cadc40,"Data Increment");
  QString::QString((QString *)&DAT_140cadc58,"Data Decrement");
  QString::QString((QString *)&DAT_140cadc70,"NRPN LSB");
  QString::QString((QString *)&DAT_140cadc88,"NRPN MSB");
  QString::QString((QString *)&DAT_140cadca0,"RPN LSB");
  QString::QString((QString *)&DAT_140cadcb8,"RPN MSB");
  QString::QString((QString *)&DAT_140cadcd0,"Undefined");
  QString::QString((QString *)&DAT_140cadce8,"Undefined");
  QString::QString((QString *)&DAT_140cadd00,"Undefined");
  QString::QString((QString *)&DAT_140cadd18,"Undefined");
  QString::QString((QString *)&DAT_140cadd30,"Undefined");
  QString::QString((QString *)&DAT_140cadd48,"Undefined");
  QString::QString((QString *)&DAT_140cadd60,"Undefined");
  QString::QString((QString *)&DAT_140cadd78,"Undefined");
  QString::QString((QString *)&DAT_140cadd90,"Undefined");
  QString::QString((QString *)&DAT_140cadda8,"Undefined");
  QString::QString((QString *)&DAT_140caddc0,"Undefined");
  QString::QString((QString *)&DAT_140caddd8,"Undefined");
  QString::QString((QString *)&DAT_140caddf0,"Undefined");
  QString::QString((QString *)&DAT_140cade08,"Undefined");
  QString::QString((QString *)&DAT_140cade20,"Undefined");
  QString::QString((QString *)&DAT_140cade38,"Undefined");
  QString::QString((QString *)&DAT_140cade50,"Undefined");
  QString::QString((QString *)&DAT_140cade68,"Undefined");
  QString::QString((QString *)&DAT_140cade80,"All Sound Off");
  QString::QString((QString *)&DAT_140cade98,"Reset All Controllers");
  QString::QString((QString *)&DAT_140cadeb0,"Local Control On/Off");
  QString::QString((QString *)&DAT_140cadec8,"All Notes Off");
  QString::QString((QString *)&DAT_140cadee0,"Omni Mode Off");
  QString::QString((QString *)&DAT_140cadef8,"Omni Mode On");
  QString::QString((QString *)&DAT_140cadf10,"Mono Mode On");
  QString::QString((QString *)&DAT_140cadf28,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050650);
  return;
}


