// FUN_14001a730 @ 14001a730

void FUN_14001a730(void)

{
  QString::QString((QString *)&DAT_140cb99f0,"Bank Select MSB");
  QString::QString((QString *)&DAT_140cb9a08,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140cb9a20,"Breath Control MSB");
  QString::QString((QString *)&DAT_140cb9a38,"Undefined");
  QString::QString((QString *)&DAT_140cb9a50,"Foot Control MSB");
  QString::QString((QString *)&DAT_140cb9a68,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140cb9a80,"Data Entry MSB");
  QString::QString((QString *)&DAT_140cb9a98,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140cb9ab0,"Balance MSB");
  QString::QString((QString *)&DAT_140cb9ac8,"Undefined");
  QString::QString((QString *)&DAT_140cb9ae0,"Pan MSB");
  QString::QString((QString *)&DAT_140cb9af8,"Expression MSB");
  QString::QString((QString *)&DAT_140cb9b10,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140cb9b28,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140cb9b40,"Undefined");
  QString::QString((QString *)&DAT_140cb9b58,"Undefined");
  QString::QString((QString *)&DAT_140cb9b70,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140cb9b88,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140cb9ba0,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140cb9bb8,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140cb9bd0,"Undefined");
  QString::QString((QString *)&DAT_140cb9be8,"Undefined");
  QString::QString((QString *)&DAT_140cb9c00,"Undefined");
  QString::QString((QString *)&DAT_140cb9c18,"Undefined");
  QString::QString((QString *)&DAT_140cb9c30,"Undefined");
  QString::QString((QString *)&DAT_140cb9c48,"Undefined");
  QString::QString((QString *)&DAT_140cb9c60,"Undefined");
  QString::QString((QString *)&DAT_140cb9c78,"Undefined");
  QString::QString((QString *)&DAT_140cb9c90,"Undefined");
  QString::QString((QString *)&DAT_140cb9ca8,"Undefined");
  QString::QString((QString *)&DAT_140cb9cc0,"Undefined");
  QString::QString((QString *)&DAT_140cb9cd8,"Undefined");
  QString::QString((QString *)&DAT_140cb9cf0,"Bank Select LSB");
  QString::QString((QString *)&DAT_140cb9d08,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140cb9d20,"Breath Control LSB");
  QString::QString((QString *)&DAT_140cb9d38,"Undefined");
  QString::QString((QString *)&DAT_140cb9d50,"Foot Control LSB");
  QString::QString((QString *)&DAT_140cb9d68,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140cb9d80,"Data Entry LSB");
  QString::QString((QString *)&DAT_140cb9d98,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140cb9db0,"Balance LSB");
  QString::QString((QString *)&DAT_140cb9dc8,"Undefined");
  QString::QString((QString *)&DAT_140cb9de0,"Pan LSB");
  QString::QString((QString *)&DAT_140cb9df8,"Expression LSB");
  QString::QString((QString *)&DAT_140cb9e10,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140cb9e28,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140cb9e40,"Undefined");
  QString::QString((QString *)&DAT_140cb9e58,"Undefined");
  QString::QString((QString *)&DAT_140cb9e70,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140cb9e88,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140cb9ea0,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140cb9eb8,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140cb9ed0,"Undefined");
  QString::QString((QString *)&DAT_140cb9ee8,"Undefined");
  QString::QString((QString *)&DAT_140cb9f00,"Undefined");
  QString::QString((QString *)&DAT_140cb9f18,"Undefined");
  QString::QString((QString *)&DAT_140cb9f30,"Undefined");
  QString::QString((QString *)&DAT_140cb9f48,"Undefined");
  QString::QString((QString *)&DAT_140cb9f60,"Undefined");
  QString::QString((QString *)&DAT_140cb9f78,"Undefined");
  QString::QString((QString *)&DAT_140cb9f90,"Undefined");
  QString::QString((QString *)&DAT_140cb9fa8,"Undefined");
  QString::QString((QString *)&DAT_140cb9fc0,"Undefined");
  QString::QString((QString *)&DAT_140cb9fd8,"Undefined");
  QString::QString((QString *)&DAT_140cb9ff0,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140cba008,"Portamento On/Off");
  QString::QString((QString *)&DAT_140cba020,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140cba038,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140cba050,"Legato Footswitch");
  QString::QString((QString *)&DAT_140cba068,"Hold 2");
  QString::QString((QString *)&DAT_140cba080,"Sound Variation");
  QString::QString((QString *)&DAT_140cba098,"Timbre");
  QString::QString((QString *)&DAT_140cba0b0,"Release Time");
  QString::QString((QString *)&DAT_140cba0c8,"Attack Time");
  QString::QString((QString *)&DAT_140cba0e0,"Brightness");
  QString::QString((QString *)&DAT_140cba0f8,"Decay Time");
  QString::QString((QString *)&DAT_140cba110,"Vibrato Rate");
  QString::QString((QString *)&DAT_140cba128,"Vibrato Depth");
  QString::QString((QString *)&DAT_140cba140,"Vibrato Delay");
  QString::QString((QString *)&DAT_140cba158,"Undefined");
  QString::QString((QString *)&DAT_140cba170,"General Purpose 5");
  QString::QString((QString *)&DAT_140cba188,"General Purpose 6");
  QString::QString((QString *)&DAT_140cba1a0,"General Purpose 7");
  QString::QString((QString *)&DAT_140cba1b8,"General Purpose 8");
  QString::QString((QString *)&DAT_140cba1d0,"Portamento Control");
  QString::QString((QString *)&DAT_140cba1e8,"Undefined");
  QString::QString((QString *)&DAT_140cba200,"Undefined");
  QString::QString((QString *)&DAT_140cba218,"Undefined");
  QString::QString((QString *)&DAT_140cba230,"High Res. Velocity");
  QString::QString((QString *)&DAT_140cba248,"Undefined");
  QString::QString((QString *)&DAT_140cba260,"Undefined");
  QString::QString((QString *)&DAT_140cba278,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140cba290,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140cba2a8,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140cba2c0,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140cba2d8,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140cba2f0,"Data Increment");
  QString::QString((QString *)&DAT_140cba308,"Data Decrement");
  QString::QString((QString *)&DAT_140cba320,"NRPN LSB");
  QString::QString((QString *)&DAT_140cba338,"NRPN MSB");
  QString::QString((QString *)&DAT_140cba350,"RPN LSB");
  QString::QString((QString *)&DAT_140cba368,"RPN MSB");
  QString::QString((QString *)&DAT_140cba380,"Undefined");
  QString::QString((QString *)&DAT_140cba398,"Undefined");
  QString::QString((QString *)&DAT_140cba3b0,"Undefined");
  QString::QString((QString *)&DAT_140cba3c8,"Undefined");
  QString::QString((QString *)&DAT_140cba3e0,"Undefined");
  QString::QString((QString *)&DAT_140cba3f8,"Undefined");
  QString::QString((QString *)&DAT_140cba410,"Undefined");
  QString::QString((QString *)&DAT_140cba428,"Undefined");
  QString::QString((QString *)&DAT_140cba440,"Undefined");
  QString::QString((QString *)&DAT_140cba458,"Undefined");
  QString::QString((QString *)&DAT_140cba470,"Undefined");
  QString::QString((QString *)&DAT_140cba488,"Undefined");
  QString::QString((QString *)&DAT_140cba4a0,"Undefined");
  QString::QString((QString *)&DAT_140cba4b8,"Undefined");
  QString::QString((QString *)&DAT_140cba4d0,"Undefined");
  QString::QString((QString *)&DAT_140cba4e8,"Undefined");
  QString::QString((QString *)&DAT_140cba500,"Undefined");
  QString::QString((QString *)&DAT_140cba518,"Undefined");
  QString::QString((QString *)&DAT_140cba530,"All Sound Off");
  QString::QString((QString *)&DAT_140cba548,"Reset All Controllers");
  QString::QString((QString *)&DAT_140cba560,"Local Control On/Off");
  QString::QString((QString *)&DAT_140cba578,"All Notes Off");
  QString::QString((QString *)&DAT_140cba590,"Omni Mode Off");
  QString::QString((QString *)&DAT_140cba5a8,"Omni Mode On");
  QString::QString((QString *)&DAT_140cba5c0,"Mono Mode On");
  QString::QString((QString *)&DAT_140cba5d8,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050e10);
  return;
}


