// FUN_14001c250 @ 14001c250

void FUN_14001c250(void)

{
  QString::QString((QString *)&DAT_140cbb2c0,"Bank Select MSB");
  QString::QString((QString *)&DAT_140cbb2d8,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140cbb2f0,"Breath Control MSB");
  QString::QString((QString *)&DAT_140cbb308,"Undefined");
  QString::QString((QString *)&DAT_140cbb320,"Foot Control MSB");
  QString::QString((QString *)&DAT_140cbb338,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140cbb350,"Data Entry MSB");
  QString::QString((QString *)&DAT_140cbb368,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140cbb380,"Balance MSB");
  QString::QString((QString *)&DAT_140cbb398,"Undefined");
  QString::QString((QString *)&DAT_140cbb3b0,"Pan MSB");
  QString::QString((QString *)&DAT_140cbb3c8,"Expression MSB");
  QString::QString((QString *)&DAT_140cbb3e0,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140cbb3f8,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140cbb410,"Undefined");
  QString::QString((QString *)&DAT_140cbb428,"Undefined");
  QString::QString((QString *)&DAT_140cbb440,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140cbb458,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140cbb470,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140cbb488,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140cbb4a0,"Undefined");
  QString::QString((QString *)&DAT_140cbb4b8,"Undefined");
  QString::QString((QString *)&DAT_140cbb4d0,"Undefined");
  QString::QString((QString *)&DAT_140cbb4e8,"Undefined");
  QString::QString((QString *)&DAT_140cbb500,"Undefined");
  QString::QString((QString *)&DAT_140cbb518,"Undefined");
  QString::QString((QString *)&DAT_140cbb530,"Undefined");
  QString::QString((QString *)&DAT_140cbb548,"Undefined");
  QString::QString((QString *)&DAT_140cbb560,"Undefined");
  QString::QString((QString *)&DAT_140cbb578,"Undefined");
  QString::QString((QString *)&DAT_140cbb590,"Undefined");
  QString::QString((QString *)&DAT_140cbb5a8,"Undefined");
  QString::QString((QString *)&DAT_140cbb5c0,"Bank Select LSB");
  QString::QString((QString *)&DAT_140cbb5d8,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140cbb5f0,"Breath Control LSB");
  QString::QString((QString *)&DAT_140cbb608,"Undefined");
  QString::QString((QString *)&DAT_140cbb620,"Foot Control LSB");
  QString::QString((QString *)&DAT_140cbb638,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140cbb650,"Data Entry LSB");
  QString::QString((QString *)&DAT_140cbb668,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140cbb680,"Balance LSB");
  QString::QString((QString *)&DAT_140cbb698,"Undefined");
  QString::QString((QString *)&DAT_140cbb6b0,"Pan LSB");
  QString::QString((QString *)&DAT_140cbb6c8,"Expression LSB");
  QString::QString((QString *)&DAT_140cbb6e0,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140cbb6f8,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140cbb710,"Undefined");
  QString::QString((QString *)&DAT_140cbb728,"Undefined");
  QString::QString((QString *)&DAT_140cbb740,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140cbb758,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140cbb770,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140cbb788,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140cbb7a0,"Undefined");
  QString::QString((QString *)&DAT_140cbb7b8,"Undefined");
  QString::QString((QString *)&DAT_140cbb7d0,"Undefined");
  QString::QString((QString *)&DAT_140cbb7e8,"Undefined");
  QString::QString((QString *)&DAT_140cbb800,"Undefined");
  QString::QString((QString *)&DAT_140cbb818,"Undefined");
  QString::QString((QString *)&DAT_140cbb830,"Undefined");
  QString::QString((QString *)&DAT_140cbb848,"Undefined");
  QString::QString((QString *)&DAT_140cbb860,"Undefined");
  QString::QString((QString *)&DAT_140cbb878,"Undefined");
  QString::QString((QString *)&DAT_140cbb890,"Undefined");
  QString::QString((QString *)&DAT_140cbb8a8,"Undefined");
  QString::QString((QString *)&DAT_140cbb8c0,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140cbb8d8,"Portamento On/Off");
  QString::QString((QString *)&DAT_140cbb8f0,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140cbb908,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140cbb920,"Legato Footswitch");
  QString::QString((QString *)&DAT_140cbb938,"Hold 2");
  QString::QString((QString *)&DAT_140cbb950,"Sound Variation");
  QString::QString((QString *)&DAT_140cbb968,"Timbre");
  QString::QString((QString *)&DAT_140cbb980,"Release Time");
  QString::QString((QString *)&DAT_140cbb998,"Attack Time");
  QString::QString((QString *)&DAT_140cbb9b0,"Brightness");
  QString::QString((QString *)&DAT_140cbb9c8,"Decay Time");
  QString::QString((QString *)&DAT_140cbb9e0,"Vibrato Rate");
  QString::QString((QString *)&DAT_140cbb9f8,"Vibrato Depth");
  QString::QString((QString *)&DAT_140cbba10,"Vibrato Delay");
  QString::QString((QString *)&DAT_140cbba28,"Undefined");
  QString::QString((QString *)&DAT_140cbba40,"General Purpose 5");
  QString::QString((QString *)&DAT_140cbba58,"General Purpose 6");
  QString::QString((QString *)&DAT_140cbba70,"General Purpose 7");
  QString::QString((QString *)&DAT_140cbba88,"General Purpose 8");
  QString::QString((QString *)&DAT_140cbbaa0,"Portamento Control");
  QString::QString((QString *)&DAT_140cbbab8,"Undefined");
  QString::QString((QString *)&DAT_140cbbad0,"Undefined");
  QString::QString((QString *)&DAT_140cbbae8,"Undefined");
  QString::QString((QString *)&DAT_140cbbb00,"High Res. Velocity");
  QString::QString((QString *)&DAT_140cbbb18,"Undefined");
  QString::QString((QString *)&DAT_140cbbb30,"Undefined");
  QString::QString((QString *)&DAT_140cbbb48,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140cbbb60,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140cbbb78,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140cbbb90,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140cbbba8,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140cbbbc0,"Data Increment");
  QString::QString((QString *)&DAT_140cbbbd8,"Data Decrement");
  QString::QString((QString *)&DAT_140cbbbf0,"NRPN LSB");
  QString::QString((QString *)&DAT_140cbbc08,"NRPN MSB");
  QString::QString((QString *)&DAT_140cbbc20,"RPN LSB");
  QString::QString((QString *)&DAT_140cbbc38,"RPN MSB");
  QString::QString((QString *)&DAT_140cbbc50,"Undefined");
  QString::QString((QString *)&DAT_140cbbc68,"Undefined");
  QString::QString((QString *)&DAT_140cbbc80,"Undefined");
  QString::QString((QString *)&DAT_140cbbc98,"Undefined");
  QString::QString((QString *)&DAT_140cbbcb0,"Undefined");
  QString::QString((QString *)&DAT_140cbbcc8,"Undefined");
  QString::QString((QString *)&DAT_140cbbce0,"Undefined");
  QString::QString((QString *)&DAT_140cbbcf8,"Undefined");
  QString::QString((QString *)&DAT_140cbbd10,"Undefined");
  QString::QString((QString *)&DAT_140cbbd28,"Undefined");
  QString::QString((QString *)&DAT_140cbbd40,"Undefined");
  QString::QString((QString *)&DAT_140cbbd58,"Undefined");
  QString::QString((QString *)&DAT_140cbbd70,"Undefined");
  QString::QString((QString *)&DAT_140cbbd88,"Undefined");
  QString::QString((QString *)&DAT_140cbbda0,"Undefined");
  QString::QString((QString *)&DAT_140cbbdb8,"Undefined");
  QString::QString((QString *)&DAT_140cbbdd0,"Undefined");
  QString::QString((QString *)&DAT_140cbbde8,"Undefined");
  QString::QString((QString *)&DAT_140cbbe00,"All Sound Off");
  QString::QString((QString *)&DAT_140cbbe18,"Reset All Controllers");
  QString::QString((QString *)&DAT_140cbbe30,"Local Control On/Off");
  QString::QString((QString *)&DAT_140cbbe48,"All Notes Off");
  QString::QString((QString *)&DAT_140cbbe60,"Omni Mode Off");
  QString::QString((QString *)&DAT_140cbbe78,"Omni Mode On");
  QString::QString((QString *)&DAT_140cbbe90,"Mono Mode On");
  QString::QString((QString *)&DAT_140cbbea8,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050f00);
  return;
}


