// FUN_1400097a0 @ 1400097a0

void FUN_1400097a0(void)

{
  QString::QString((QString *)&DAT_140caa190,"Bank Select MSB");
  QString::QString((QString *)&DAT_140caa1a8,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140caa1c0,"Breath Control MSB");
  QString::QString((QString *)&DAT_140caa1d8,"Undefined");
  QString::QString((QString *)&DAT_140caa1f0,"Foot Control MSB");
  QString::QString((QString *)&DAT_140caa208,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140caa220,"Data Entry MSB");
  QString::QString((QString *)&DAT_140caa238,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140caa250,"Balance MSB");
  QString::QString((QString *)&DAT_140caa268,"Undefined");
  QString::QString((QString *)&DAT_140caa280,"Pan MSB");
  QString::QString((QString *)&DAT_140caa298,"Expression MSB");
  QString::QString((QString *)&DAT_140caa2b0,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140caa2c8,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140caa2e0,"Undefined");
  QString::QString((QString *)&DAT_140caa2f8,"Undefined");
  QString::QString((QString *)&DAT_140caa310,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140caa328,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140caa340,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140caa358,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140caa370,"Undefined");
  QString::QString((QString *)&DAT_140caa388,"Undefined");
  QString::QString((QString *)&DAT_140caa3a0,"Undefined");
  QString::QString((QString *)&DAT_140caa3b8,"Undefined");
  QString::QString((QString *)&DAT_140caa3d0,"Undefined");
  QString::QString((QString *)&DAT_140caa3e8,"Undefined");
  QString::QString((QString *)&DAT_140caa400,"Undefined");
  QString::QString((QString *)&DAT_140caa418,"Undefined");
  QString::QString((QString *)&DAT_140caa430,"Undefined");
  QString::QString((QString *)&DAT_140caa448,"Undefined");
  QString::QString((QString *)&DAT_140caa460,"Undefined");
  QString::QString((QString *)&DAT_140caa478,"Undefined");
  QString::QString((QString *)&DAT_140caa490,"Bank Select LSB");
  QString::QString((QString *)&DAT_140caa4a8,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140caa4c0,"Breath Control LSB");
  QString::QString((QString *)&DAT_140caa4d8,"Undefined");
  QString::QString((QString *)&DAT_140caa4f0,"Foot Control LSB");
  QString::QString((QString *)&DAT_140caa508,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140caa520,"Data Entry LSB");
  QString::QString((QString *)&DAT_140caa538,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140caa550,"Balance LSB");
  QString::QString((QString *)&DAT_140caa568,"Undefined");
  QString::QString((QString *)&DAT_140caa580,"Pan LSB");
  QString::QString((QString *)&DAT_140caa598,"Expression LSB");
  QString::QString((QString *)&DAT_140caa5b0,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140caa5c8,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140caa5e0,"Undefined");
  QString::QString((QString *)&DAT_140caa5f8,"Undefined");
  QString::QString((QString *)&DAT_140caa610,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140caa628,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140caa640,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140caa658,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140caa670,"Undefined");
  QString::QString((QString *)&DAT_140caa688,"Undefined");
  QString::QString((QString *)&DAT_140caa6a0,"Undefined");
  QString::QString((QString *)&DAT_140caa6b8,"Undefined");
  QString::QString((QString *)&DAT_140caa6d0,"Undefined");
  QString::QString((QString *)&DAT_140caa6e8,"Undefined");
  QString::QString((QString *)&DAT_140caa700,"Undefined");
  QString::QString((QString *)&DAT_140caa718,"Undefined");
  QString::QString((QString *)&DAT_140caa730,"Undefined");
  QString::QString((QString *)&DAT_140caa748,"Undefined");
  QString::QString((QString *)&DAT_140caa760,"Undefined");
  QString::QString((QString *)&DAT_140caa778,"Undefined");
  QString::QString((QString *)&DAT_140caa790,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140caa7a8,"Portamento On/Off");
  QString::QString((QString *)&DAT_140caa7c0,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140caa7d8,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140caa7f0,"Legato Footswitch");
  QString::QString((QString *)&DAT_140caa808,"Hold 2");
  QString::QString((QString *)&DAT_140caa820,"Sound Variation");
  QString::QString((QString *)&DAT_140caa838,"Timbre");
  QString::QString((QString *)&DAT_140caa850,"Release Time");
  QString::QString((QString *)&DAT_140caa868,"Attack Time");
  QString::QString((QString *)&DAT_140caa880,"Brightness");
  QString::QString((QString *)&DAT_140caa898,"Decay Time");
  QString::QString((QString *)&DAT_140caa8b0,"Vibrato Rate");
  QString::QString((QString *)&DAT_140caa8c8,"Vibrato Depth");
  QString::QString((QString *)&DAT_140caa8e0,"Vibrato Delay");
  QString::QString((QString *)&DAT_140caa8f8,"Undefined");
  QString::QString((QString *)&DAT_140caa910,"General Purpose 5");
  QString::QString((QString *)&DAT_140caa928,"General Purpose 6");
  QString::QString((QString *)&DAT_140caa940,"General Purpose 7");
  QString::QString((QString *)&DAT_140caa958,"General Purpose 8");
  QString::QString((QString *)&DAT_140caa970,"Portamento Control");
  QString::QString((QString *)&DAT_140caa988,"Undefined");
  QString::QString((QString *)&DAT_140caa9a0,"Undefined");
  QString::QString((QString *)&DAT_140caa9b8,"Undefined");
  QString::QString((QString *)&DAT_140caa9d0,"High Res. Velocity");
  QString::QString((QString *)&DAT_140caa9e8,"Undefined");
  QString::QString((QString *)&DAT_140caaa00,"Undefined");
  QString::QString((QString *)&DAT_140caaa18,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140caaa30,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140caaa48,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140caaa60,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140caaa78,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140caaa90,"Data Increment");
  QString::QString((QString *)&DAT_140caaaa8,"Data Decrement");
  QString::QString((QString *)&DAT_140caaac0,"NRPN LSB");
  QString::QString((QString *)&DAT_140caaad8,"NRPN MSB");
  QString::QString((QString *)&DAT_140caaaf0,"RPN LSB");
  QString::QString((QString *)&DAT_140caab08,"RPN MSB");
  QString::QString((QString *)&DAT_140caab20,"Undefined");
  QString::QString((QString *)&DAT_140caab38,"Undefined");
  QString::QString((QString *)&DAT_140caab50,"Undefined");
  QString::QString((QString *)&DAT_140caab68,"Undefined");
  QString::QString((QString *)&DAT_140caab80,"Undefined");
  QString::QString((QString *)&DAT_140caab98,"Undefined");
  QString::QString((QString *)&DAT_140caabb0,"Undefined");
  QString::QString((QString *)&DAT_140caabc8,"Undefined");
  QString::QString((QString *)&DAT_140caabe0,"Undefined");
  QString::QString((QString *)&DAT_140caabf8,"Undefined");
  QString::QString((QString *)&DAT_140caac10,"Undefined");
  QString::QString((QString *)&DAT_140caac28,"Undefined");
  QString::QString((QString *)&DAT_140caac40,"Undefined");
  QString::QString((QString *)&DAT_140caac58,"Undefined");
  QString::QString((QString *)&DAT_140caac70,"Undefined");
  QString::QString((QString *)&DAT_140caac88,"Undefined");
  QString::QString((QString *)&DAT_140caaca0,"Undefined");
  QString::QString((QString *)&DAT_140caacb8,"Undefined");
  QString::QString((QString *)&DAT_140caacd0,"All Sound Off");
  QString::QString((QString *)&DAT_140caace8,"Reset All Controllers");
  QString::QString((QString *)&DAT_140caad00,"Local Control On/Off");
  QString::QString((QString *)&DAT_140caad18,"All Notes Off");
  QString::QString((QString *)&DAT_140caad30,"Omni Mode Off");
  QString::QString((QString *)&DAT_140caad48,"Omni Mode On");
  QString::QString((QString *)&DAT_140caad60,"Mono Mode On");
  QString::QString((QString *)&DAT_140caad78,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050470);
  return;
}


