// FUN_14001dd70 @ 14001dd70

void FUN_14001dd70(void)

{
  QString::QString((QString *)&DAT_140cbcb90,"Bank Select MSB");
  QString::QString((QString *)&DAT_140cbcba8,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140cbcbc0,"Breath Control MSB");
  QString::QString((QString *)&DAT_140cbcbd8,"Undefined");
  QString::QString((QString *)&DAT_140cbcbf0,"Foot Control MSB");
  QString::QString((QString *)&DAT_140cbcc08,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140cbcc20,"Data Entry MSB");
  QString::QString((QString *)&DAT_140cbcc38,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140cbcc50,"Balance MSB");
  QString::QString((QString *)&DAT_140cbcc68,"Undefined");
  QString::QString((QString *)&DAT_140cbcc80,"Pan MSB");
  QString::QString((QString *)&DAT_140cbcc98,"Expression MSB");
  QString::QString((QString *)&DAT_140cbccb0,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140cbccc8,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140cbcce0,"Undefined");
  QString::QString((QString *)&DAT_140cbccf8,"Undefined");
  QString::QString((QString *)&DAT_140cbcd10,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140cbcd28,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140cbcd40,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140cbcd58,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140cbcd70,"Undefined");
  QString::QString((QString *)&DAT_140cbcd88,"Undefined");
  QString::QString((QString *)&DAT_140cbcda0,"Undefined");
  QString::QString((QString *)&DAT_140cbcdb8,"Undefined");
  QString::QString((QString *)&DAT_140cbcdd0,"Undefined");
  QString::QString((QString *)&DAT_140cbcde8,"Undefined");
  QString::QString((QString *)&DAT_140cbce00,"Undefined");
  QString::QString((QString *)&DAT_140cbce18,"Undefined");
  QString::QString((QString *)&DAT_140cbce30,"Undefined");
  QString::QString((QString *)&DAT_140cbce48,"Undefined");
  QString::QString((QString *)&DAT_140cbce60,"Undefined");
  QString::QString((QString *)&DAT_140cbce78,"Undefined");
  QString::QString((QString *)&DAT_140cbce90,"Bank Select LSB");
  QString::QString((QString *)&DAT_140cbcea8,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140cbcec0,"Breath Control LSB");
  QString::QString((QString *)&DAT_140cbced8,"Undefined");
  QString::QString((QString *)&DAT_140cbcef0,"Foot Control LSB");
  QString::QString((QString *)&DAT_140cbcf08,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140cbcf20,"Data Entry LSB");
  QString::QString((QString *)&DAT_140cbcf38,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140cbcf50,"Balance LSB");
  QString::QString((QString *)&DAT_140cbcf68,"Undefined");
  QString::QString((QString *)&DAT_140cbcf80,"Pan LSB");
  QString::QString((QString *)&DAT_140cbcf98,"Expression LSB");
  QString::QString((QString *)&DAT_140cbcfb0,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140cbcfc8,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140cbcfe0,"Undefined");
  QString::QString((QString *)&DAT_140cbcff8,"Undefined");
  QString::QString((QString *)&DAT_140cbd010,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140cbd028,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140cbd040,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140cbd058,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140cbd070,"Undefined");
  QString::QString((QString *)&DAT_140cbd088,"Undefined");
  QString::QString((QString *)&DAT_140cbd0a0,"Undefined");
  QString::QString((QString *)&DAT_140cbd0b8,"Undefined");
  QString::QString((QString *)&DAT_140cbd0d0,"Undefined");
  QString::QString((QString *)&DAT_140cbd0e8,"Undefined");
  QString::QString((QString *)&DAT_140cbd100,"Undefined");
  QString::QString((QString *)&DAT_140cbd118,"Undefined");
  QString::QString((QString *)&DAT_140cbd130,"Undefined");
  QString::QString((QString *)&DAT_140cbd148,"Undefined");
  QString::QString((QString *)&DAT_140cbd160,"Undefined");
  QString::QString((QString *)&DAT_140cbd178,"Undefined");
  QString::QString((QString *)&DAT_140cbd190,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140cbd1a8,"Portamento On/Off");
  QString::QString((QString *)&DAT_140cbd1c0,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140cbd1d8,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140cbd1f0,"Legato Footswitch");
  QString::QString((QString *)&DAT_140cbd208,"Hold 2");
  QString::QString((QString *)&DAT_140cbd220,"Sound Variation");
  QString::QString((QString *)&DAT_140cbd238,"Timbre");
  QString::QString((QString *)&DAT_140cbd250,"Release Time");
  QString::QString((QString *)&DAT_140cbd268,"Attack Time");
  QString::QString((QString *)&DAT_140cbd280,"Brightness");
  QString::QString((QString *)&DAT_140cbd298,"Decay Time");
  QString::QString((QString *)&DAT_140cbd2b0,"Vibrato Rate");
  QString::QString((QString *)&DAT_140cbd2c8,"Vibrato Depth");
  QString::QString((QString *)&DAT_140cbd2e0,"Vibrato Delay");
  QString::QString((QString *)&DAT_140cbd2f8,"Undefined");
  QString::QString((QString *)&DAT_140cbd310,"General Purpose 5");
  QString::QString((QString *)&DAT_140cbd328,"General Purpose 6");
  QString::QString((QString *)&DAT_140cbd340,"General Purpose 7");
  QString::QString((QString *)&DAT_140cbd358,"General Purpose 8");
  QString::QString((QString *)&DAT_140cbd370,"Portamento Control");
  QString::QString((QString *)&DAT_140cbd388,"Undefined");
  QString::QString((QString *)&DAT_140cbd3a0,"Undefined");
  QString::QString((QString *)&DAT_140cbd3b8,"Undefined");
  QString::QString((QString *)&DAT_140cbd3d0,"High Res. Velocity");
  QString::QString((QString *)&DAT_140cbd3e8,"Undefined");
  QString::QString((QString *)&DAT_140cbd400,"Undefined");
  QString::QString((QString *)&DAT_140cbd418,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140cbd430,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140cbd448,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140cbd460,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140cbd478,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140cbd490,"Data Increment");
  QString::QString((QString *)&DAT_140cbd4a8,"Data Decrement");
  QString::QString((QString *)&DAT_140cbd4c0,"NRPN LSB");
  QString::QString((QString *)&DAT_140cbd4d8,"NRPN MSB");
  QString::QString((QString *)&DAT_140cbd4f0,"RPN LSB");
  QString::QString((QString *)&DAT_140cbd508,"RPN MSB");
  QString::QString((QString *)&DAT_140cbd520,"Undefined");
  QString::QString((QString *)&DAT_140cbd538,"Undefined");
  QString::QString((QString *)&DAT_140cbd550,"Undefined");
  QString::QString((QString *)&DAT_140cbd568,"Undefined");
  QString::QString((QString *)&DAT_140cbd580,"Undefined");
  QString::QString((QString *)&DAT_140cbd598,"Undefined");
  QString::QString((QString *)&DAT_140cbd5b0,"Undefined");
  QString::QString((QString *)&DAT_140cbd5c8,"Undefined");
  QString::QString((QString *)&DAT_140cbd5e0,"Undefined");
  QString::QString((QString *)&DAT_140cbd5f8,"Undefined");
  QString::QString((QString *)&DAT_140cbd610,"Undefined");
  QString::QString((QString *)&DAT_140cbd628,"Undefined");
  QString::QString((QString *)&DAT_140cbd640,"Undefined");
  QString::QString((QString *)&DAT_140cbd658,"Undefined");
  QString::QString((QString *)&DAT_140cbd670,"Undefined");
  QString::QString((QString *)&DAT_140cbd688,"Undefined");
  QString::QString((QString *)&DAT_140cbd6a0,"Undefined");
  QString::QString((QString *)&DAT_140cbd6b8,"Undefined");
  QString::QString((QString *)&DAT_140cbd6d0,"All Sound Off");
  QString::QString((QString *)&DAT_140cbd6e8,"Reset All Controllers");
  QString::QString((QString *)&DAT_140cbd700,"Local Control On/Off");
  QString::QString((QString *)&DAT_140cbd718,"All Notes Off");
  QString::QString((QString *)&DAT_140cbd730,"Omni Mode Off");
  QString::QString((QString *)&DAT_140cbd748,"Omni Mode On");
  QString::QString((QString *)&DAT_140cbd760,"Mono Mode On");
  QString::QString((QString *)&DAT_140cbd778,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050ff0);
  return;
}


