// FUN_14001f890 @ 14001f890

void FUN_14001f890(void)

{
  QString::QString((QString *)&DAT_140cbe460,"Bank Select MSB");
  QString::QString((QString *)&DAT_140cbe478,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140cbe490,"Breath Control MSB");
  QString::QString((QString *)&DAT_140cbe4a8,"Undefined");
  QString::QString((QString *)&DAT_140cbe4c0,"Foot Control MSB");
  QString::QString((QString *)&DAT_140cbe4d8,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140cbe4f0,"Data Entry MSB");
  QString::QString((QString *)&DAT_140cbe508,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140cbe520,"Balance MSB");
  QString::QString((QString *)&DAT_140cbe538,"Undefined");
  QString::QString((QString *)&DAT_140cbe550,"Pan MSB");
  QString::QString((QString *)&DAT_140cbe568,"Expression MSB");
  QString::QString((QString *)&DAT_140cbe580,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140cbe598,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140cbe5b0,"Undefined");
  QString::QString((QString *)&DAT_140cbe5c8,"Undefined");
  QString::QString((QString *)&DAT_140cbe5e0,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140cbe5f8,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140cbe610,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140cbe628,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140cbe640,"Undefined");
  QString::QString((QString *)&DAT_140cbe658,"Undefined");
  QString::QString((QString *)&DAT_140cbe670,"Undefined");
  QString::QString((QString *)&DAT_140cbe688,"Undefined");
  QString::QString((QString *)&DAT_140cbe6a0,"Undefined");
  QString::QString((QString *)&DAT_140cbe6b8,"Undefined");
  QString::QString((QString *)&DAT_140cbe6d0,"Undefined");
  QString::QString((QString *)&DAT_140cbe6e8,"Undefined");
  QString::QString((QString *)&DAT_140cbe700,"Undefined");
  QString::QString((QString *)&DAT_140cbe718,"Undefined");
  QString::QString((QString *)&DAT_140cbe730,"Undefined");
  QString::QString((QString *)&DAT_140cbe748,"Undefined");
  QString::QString((QString *)&DAT_140cbe760,"Bank Select LSB");
  QString::QString((QString *)&DAT_140cbe778,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140cbe790,"Breath Control LSB");
  QString::QString((QString *)&DAT_140cbe7a8,"Undefined");
  QString::QString((QString *)&DAT_140cbe7c0,"Foot Control LSB");
  QString::QString((QString *)&DAT_140cbe7d8,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140cbe7f0,"Data Entry LSB");
  QString::QString((QString *)&DAT_140cbe808,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140cbe820,"Balance LSB");
  QString::QString((QString *)&DAT_140cbe838,"Undefined");
  QString::QString((QString *)&DAT_140cbe850,"Pan LSB");
  QString::QString((QString *)&DAT_140cbe868,"Expression LSB");
  QString::QString((QString *)&DAT_140cbe880,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140cbe898,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140cbe8b0,"Undefined");
  QString::QString((QString *)&DAT_140cbe8c8,"Undefined");
  QString::QString((QString *)&DAT_140cbe8e0,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140cbe8f8,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140cbe910,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140cbe928,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140cbe940,"Undefined");
  QString::QString((QString *)&DAT_140cbe958,"Undefined");
  QString::QString((QString *)&DAT_140cbe970,"Undefined");
  QString::QString((QString *)&DAT_140cbe988,"Undefined");
  QString::QString((QString *)&DAT_140cbe9a0,"Undefined");
  QString::QString((QString *)&DAT_140cbe9b8,"Undefined");
  QString::QString((QString *)&DAT_140cbe9d0,"Undefined");
  QString::QString((QString *)&DAT_140cbe9e8,"Undefined");
  QString::QString((QString *)&DAT_140cbea00,"Undefined");
  QString::QString((QString *)&DAT_140cbea18,"Undefined");
  QString::QString((QString *)&DAT_140cbea30,"Undefined");
  QString::QString((QString *)&DAT_140cbea48,"Undefined");
  QString::QString((QString *)&DAT_140cbea60,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140cbea78,"Portamento On/Off");
  QString::QString((QString *)&DAT_140cbea90,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140cbeaa8,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140cbeac0,"Legato Footswitch");
  QString::QString((QString *)&DAT_140cbead8,"Hold 2");
  QString::QString((QString *)&DAT_140cbeaf0,"Sound Variation");
  QString::QString((QString *)&DAT_140cbeb08,"Timbre");
  QString::QString((QString *)&DAT_140cbeb20,"Release Time");
  QString::QString((QString *)&DAT_140cbeb38,"Attack Time");
  QString::QString((QString *)&DAT_140cbeb50,"Brightness");
  QString::QString((QString *)&DAT_140cbeb68,"Decay Time");
  QString::QString((QString *)&DAT_140cbeb80,"Vibrato Rate");
  QString::QString((QString *)&DAT_140cbeb98,"Vibrato Depth");
  QString::QString((QString *)&DAT_140cbebb0,"Vibrato Delay");
  QString::QString((QString *)&DAT_140cbebc8,"Undefined");
  QString::QString((QString *)&DAT_140cbebe0,"General Purpose 5");
  QString::QString((QString *)&DAT_140cbebf8,"General Purpose 6");
  QString::QString((QString *)&DAT_140cbec10,"General Purpose 7");
  QString::QString((QString *)&DAT_140cbec28,"General Purpose 8");
  QString::QString((QString *)&DAT_140cbec40,"Portamento Control");
  QString::QString((QString *)&DAT_140cbec58,"Undefined");
  QString::QString((QString *)&DAT_140cbec70,"Undefined");
  QString::QString((QString *)&DAT_140cbec88,"Undefined");
  QString::QString((QString *)&DAT_140cbeca0,"High Res. Velocity");
  QString::QString((QString *)&DAT_140cbecb8,"Undefined");
  QString::QString((QString *)&DAT_140cbecd0,"Undefined");
  QString::QString((QString *)&DAT_140cbece8,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140cbed00,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140cbed18,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140cbed30,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140cbed48,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140cbed60,"Data Increment");
  QString::QString((QString *)&DAT_140cbed78,"Data Decrement");
  QString::QString((QString *)&DAT_140cbed90,"NRPN LSB");
  QString::QString((QString *)&DAT_140cbeda8,"NRPN MSB");
  QString::QString((QString *)&DAT_140cbedc0,"RPN LSB");
  QString::QString((QString *)&DAT_140cbedd8,"RPN MSB");
  QString::QString((QString *)&DAT_140cbedf0,"Undefined");
  QString::QString((QString *)&DAT_140cbee08,"Undefined");
  QString::QString((QString *)&DAT_140cbee20,"Undefined");
  QString::QString((QString *)&DAT_140cbee38,"Undefined");
  QString::QString((QString *)&DAT_140cbee50,"Undefined");
  QString::QString((QString *)&DAT_140cbee68,"Undefined");
  QString::QString((QString *)&DAT_140cbee80,"Undefined");
  QString::QString((QString *)&DAT_140cbee98,"Undefined");
  QString::QString((QString *)&DAT_140cbeeb0,"Undefined");
  QString::QString((QString *)&DAT_140cbeec8,"Undefined");
  QString::QString((QString *)&DAT_140cbeee0,"Undefined");
  QString::QString((QString *)&DAT_140cbeef8,"Undefined");
  QString::QString((QString *)&DAT_140cbef10,"Undefined");
  QString::QString((QString *)&DAT_140cbef28,"Undefined");
  QString::QString((QString *)&DAT_140cbef40,"Undefined");
  QString::QString((QString *)&DAT_140cbef58,"Undefined");
  QString::QString((QString *)&DAT_140cbef70,"Undefined");
  QString::QString((QString *)&DAT_140cbef88,"Undefined");
  QString::QString((QString *)&DAT_140cbefa0,"All Sound Off");
  QString::QString((QString *)&DAT_140cbefb8,"Reset All Controllers");
  QString::QString((QString *)&DAT_140cbefd0,"Local Control On/Off");
  QString::QString((QString *)&DAT_140cbefe8,"All Notes Off");
  QString::QString((QString *)&DAT_140cbf000,"Omni Mode Off");
  QString::QString((QString *)&DAT_140cbf018,"Omni Mode On");
  QString::QString((QString *)&DAT_140cbf030,"Mono Mode On");
  QString::QString((QString *)&DAT_140cbf048,"Poly Mode On");
  atexit((_func_5014 *)&LAB_1400510e0);
  return;
}


