// FUN_14000b2c0 @ 14000b2c0

void FUN_14000b2c0(void)

{
  QString::QString((QString *)&DAT_140caba60,"Bank Select MSB");
  QString::QString((QString *)&DAT_140caba78,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140caba90,"Breath Control MSB");
  QString::QString((QString *)&DAT_140cabaa8,"Undefined");
  QString::QString((QString *)&DAT_140cabac0,"Foot Control MSB");
  QString::QString((QString *)&DAT_140cabad8,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140cabaf0,"Data Entry MSB");
  QString::QString((QString *)&DAT_140cabb08,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140cabb20,"Balance MSB");
  QString::QString((QString *)&DAT_140cabb38,"Undefined");
  QString::QString((QString *)&DAT_140cabb50,"Pan MSB");
  QString::QString((QString *)&DAT_140cabb68,"Expression MSB");
  QString::QString((QString *)&DAT_140cabb80,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140cabb98,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140cabbb0,"Undefined");
  QString::QString((QString *)&DAT_140cabbc8,"Undefined");
  QString::QString((QString *)&DAT_140cabbe0,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140cabbf8,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140cabc10,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140cabc28,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140cabc40,"Undefined");
  QString::QString((QString *)&DAT_140cabc58,"Undefined");
  QString::QString((QString *)&DAT_140cabc70,"Undefined");
  QString::QString((QString *)&DAT_140cabc88,"Undefined");
  QString::QString((QString *)&DAT_140cabca0,"Undefined");
  QString::QString((QString *)&DAT_140cabcb8,"Undefined");
  QString::QString((QString *)&DAT_140cabcd0,"Undefined");
  QString::QString((QString *)&DAT_140cabce8,"Undefined");
  QString::QString((QString *)&DAT_140cabd00,"Undefined");
  QString::QString((QString *)&DAT_140cabd18,"Undefined");
  QString::QString((QString *)&DAT_140cabd30,"Undefined");
  QString::QString((QString *)&DAT_140cabd48,"Undefined");
  QString::QString((QString *)&DAT_140cabd60,"Bank Select LSB");
  QString::QString((QString *)&DAT_140cabd78,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140cabd90,"Breath Control LSB");
  QString::QString((QString *)&DAT_140cabda8,"Undefined");
  QString::QString((QString *)&DAT_140cabdc0,"Foot Control LSB");
  QString::QString((QString *)&DAT_140cabdd8,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140cabdf0,"Data Entry LSB");
  QString::QString((QString *)&DAT_140cabe08,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140cabe20,"Balance LSB");
  QString::QString((QString *)&DAT_140cabe38,"Undefined");
  QString::QString((QString *)&DAT_140cabe50,"Pan LSB");
  QString::QString((QString *)&DAT_140cabe68,"Expression LSB");
  QString::QString((QString *)&DAT_140cabe80,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140cabe98,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140cabeb0,"Undefined");
  QString::QString((QString *)&DAT_140cabec8,"Undefined");
  QString::QString((QString *)&DAT_140cabee0,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140cabef8,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140cabf10,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140cabf28,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140cabf40,"Undefined");
  QString::QString((QString *)&DAT_140cabf58,"Undefined");
  QString::QString((QString *)&DAT_140cabf70,"Undefined");
  QString::QString((QString *)&DAT_140cabf88,"Undefined");
  QString::QString((QString *)&DAT_140cabfa0,"Undefined");
  QString::QString((QString *)&DAT_140cabfb8,"Undefined");
  QString::QString((QString *)&DAT_140cabfd0,"Undefined");
  QString::QString((QString *)&DAT_140cabfe8,"Undefined");
  QString::QString((QString *)&DAT_140cac000,"Undefined");
  QString::QString((QString *)&DAT_140cac018,"Undefined");
  QString::QString((QString *)&DAT_140cac030,"Undefined");
  QString::QString((QString *)&DAT_140cac048,"Undefined");
  QString::QString((QString *)&DAT_140cac060,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140cac078,"Portamento On/Off");
  QString::QString((QString *)&DAT_140cac090,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140cac0a8,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140cac0c0,"Legato Footswitch");
  QString::QString((QString *)&DAT_140cac0d8,"Hold 2");
  QString::QString((QString *)&DAT_140cac0f0,"Sound Variation");
  QString::QString((QString *)&DAT_140cac108,"Timbre");
  QString::QString((QString *)&DAT_140cac120,"Release Time");
  QString::QString((QString *)&DAT_140cac138,"Attack Time");
  QString::QString((QString *)&DAT_140cac150,"Brightness");
  QString::QString((QString *)&DAT_140cac168,"Decay Time");
  QString::QString((QString *)&DAT_140cac180,"Vibrato Rate");
  QString::QString((QString *)&DAT_140cac198,"Vibrato Depth");
  QString::QString((QString *)&DAT_140cac1b0,"Vibrato Delay");
  QString::QString((QString *)&DAT_140cac1c8,"Undefined");
  QString::QString((QString *)&DAT_140cac1e0,"General Purpose 5");
  QString::QString((QString *)&DAT_140cac1f8,"General Purpose 6");
  QString::QString((QString *)&DAT_140cac210,"General Purpose 7");
  QString::QString((QString *)&DAT_140cac228,"General Purpose 8");
  QString::QString((QString *)&DAT_140cac240,"Portamento Control");
  QString::QString((QString *)&DAT_140cac258,"Undefined");
  QString::QString((QString *)&DAT_140cac270,"Undefined");
  QString::QString((QString *)&DAT_140cac288,"Undefined");
  QString::QString((QString *)&DAT_140cac2a0,"High Res. Velocity");
  QString::QString((QString *)&DAT_140cac2b8,"Undefined");
  QString::QString((QString *)&DAT_140cac2d0,"Undefined");
  QString::QString((QString *)&DAT_140cac2e8,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140cac300,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140cac318,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140cac330,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140cac348,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140cac360,"Data Increment");
  QString::QString((QString *)&DAT_140cac378,"Data Decrement");
  QString::QString((QString *)&DAT_140cac390,"NRPN LSB");
  QString::QString((QString *)&DAT_140cac3a8,"NRPN MSB");
  QString::QString((QString *)&DAT_140cac3c0,"RPN LSB");
  QString::QString((QString *)&DAT_140cac3d8,"RPN MSB");
  QString::QString((QString *)&DAT_140cac3f0,"Undefined");
  QString::QString((QString *)&DAT_140cac408,"Undefined");
  QString::QString((QString *)&DAT_140cac420,"Undefined");
  QString::QString((QString *)&DAT_140cac438,"Undefined");
  QString::QString((QString *)&DAT_140cac450,"Undefined");
  QString::QString((QString *)&DAT_140cac468,"Undefined");
  QString::QString((QString *)&DAT_140cac480,"Undefined");
  QString::QString((QString *)&DAT_140cac498,"Undefined");
  QString::QString((QString *)&DAT_140cac4b0,"Undefined");
  QString::QString((QString *)&DAT_140cac4c8,"Undefined");
  QString::QString((QString *)&DAT_140cac4e0,"Undefined");
  QString::QString((QString *)&DAT_140cac4f8,"Undefined");
  QString::QString((QString *)&DAT_140cac510,"Undefined");
  QString::QString((QString *)&DAT_140cac528,"Undefined");
  QString::QString((QString *)&DAT_140cac540,"Undefined");
  QString::QString((QString *)&DAT_140cac558,"Undefined");
  QString::QString((QString *)&DAT_140cac570,"Undefined");
  QString::QString((QString *)&DAT_140cac588,"Undefined");
  QString::QString((QString *)&DAT_140cac5a0,"All Sound Off");
  QString::QString((QString *)&DAT_140cac5b8,"Reset All Controllers");
  QString::QString((QString *)&DAT_140cac5d0,"Local Control On/Off");
  QString::QString((QString *)&DAT_140cac5e8,"All Notes Off");
  QString::QString((QString *)&DAT_140cac600,"Omni Mode Off");
  QString::QString((QString *)&DAT_140cac618,"Omni Mode On");
  QString::QString((QString *)&DAT_140cac630,"Mono Mode On");
  QString::QString((QString *)&DAT_140cac648,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050560);
  return;
}


