// FUN_14000e900 @ 14000e900

void FUN_14000e900(void)

{
  QString::QString((QString *)&DAT_140caec20,"Bank Select MSB");
  QString::QString((QString *)&DAT_140caec38,"Modulation Wheel MSB");
  QString::QString((QString *)&DAT_140caec50,"Breath Control MSB");
  QString::QString((QString *)&DAT_140caec68,"Undefined");
  QString::QString((QString *)&DAT_140caec80,"Foot Control MSB");
  QString::QString((QString *)&DAT_140caec98,"Portamento Time MSB");
  QString::QString((QString *)&DAT_140caecb0,"Data Entry MSB");
  QString::QString((QString *)&DAT_140caecc8,"Channel Volume MSB");
  QString::QString((QString *)&DAT_140caece0,"Balance MSB");
  QString::QString((QString *)&DAT_140caecf8,"Undefined");
  QString::QString((QString *)&DAT_140caed10,"Pan MSB");
  QString::QString((QString *)&DAT_140caed28,"Expression MSB");
  QString::QString((QString *)&DAT_140caed40,"Effect Control 1MSB");
  QString::QString((QString *)&DAT_140caed58,"Effect Control 2 MSB");
  QString::QString((QString *)&DAT_140caed70,"Undefined");
  QString::QString((QString *)&DAT_140caed88,"Undefined");
  QString::QString((QString *)&DAT_140caeda0,"General Purpose 1 MSB");
  QString::QString((QString *)&DAT_140caedb8,"General Purpose 2 MSB");
  QString::QString((QString *)&DAT_140caedd0,"General Purpose 3 MSB");
  QString::QString((QString *)&DAT_140caede8,"General Purpose 4 MSB");
  QString::QString((QString *)&DAT_140caee00,"Undefined");
  QString::QString((QString *)&DAT_140caee18,"Undefined");
  QString::QString((QString *)&DAT_140caee30,"Undefined");
  QString::QString((QString *)&DAT_140caee48,"Undefined");
  QString::QString((QString *)&DAT_140caee60,"Undefined");
  QString::QString((QString *)&DAT_140caee78,"Undefined");
  QString::QString((QString *)&DAT_140caee90,"Undefined");
  QString::QString((QString *)&DAT_140caeea8,"Undefined");
  QString::QString((QString *)&DAT_140caeec0,"Undefined");
  QString::QString((QString *)&DAT_140caeed8,"Undefined");
  QString::QString((QString *)&DAT_140caeef0,"Undefined");
  QString::QString((QString *)&DAT_140caef08,"Undefined");
  QString::QString((QString *)&DAT_140caef20,"Bank Select LSB");
  QString::QString((QString *)&DAT_140caef38,"Modulation Wheel LSB");
  QString::QString((QString *)&DAT_140caef50,"Breath Control LSB");
  QString::QString((QString *)&DAT_140caef68,"Undefined");
  QString::QString((QString *)&DAT_140caef80,"Foot Control LSB");
  QString::QString((QString *)&DAT_140caef98,"Portamento Time LSB");
  QString::QString((QString *)&DAT_140caefb0,"Data Entry LSB");
  QString::QString((QString *)&DAT_140caefc8,"Channel Volume LSB");
  QString::QString((QString *)&DAT_140caefe0,"Balance LSB");
  QString::QString((QString *)&DAT_140caeff8,"Undefined");
  QString::QString((QString *)&DAT_140caf010,"Pan LSB");
  QString::QString((QString *)&DAT_140caf028,"Expression LSB");
  QString::QString((QString *)&DAT_140caf040,"Effect Control 1 LSB");
  QString::QString((QString *)&DAT_140caf058,"Effect Control 2 LSB");
  QString::QString((QString *)&DAT_140caf070,"Undefined");
  QString::QString((QString *)&DAT_140caf088,"Undefined");
  QString::QString((QString *)&DAT_140caf0a0,"General Purpose 1 LSB");
  QString::QString((QString *)&DAT_140caf0b8,"General Purpose 2 LSB");
  QString::QString((QString *)&DAT_140caf0d0,"General Purpose 3 LSB");
  QString::QString((QString *)&DAT_140caf0e8,"General Purpose 4 LSB");
  QString::QString((QString *)&DAT_140caf100,"Undefined");
  QString::QString((QString *)&DAT_140caf118,"Undefined");
  QString::QString((QString *)&DAT_140caf130,"Undefined");
  QString::QString((QString *)&DAT_140caf148,"Undefined");
  QString::QString((QString *)&DAT_140caf160,"Undefined");
  QString::QString((QString *)&DAT_140caf178,"Undefined");
  QString::QString((QString *)&DAT_140caf190,"Undefined");
  QString::QString((QString *)&DAT_140caf1a8,"Undefined");
  QString::QString((QString *)&DAT_140caf1c0,"Undefined");
  QString::QString((QString *)&DAT_140caf1d8,"Undefined");
  QString::QString((QString *)&DAT_140caf1f0,"Undefined");
  QString::QString((QString *)&DAT_140caf208,"Undefined");
  QString::QString((QString *)&DAT_140caf220,"Sustain Pedal On/Off");
  QString::QString((QString *)&DAT_140caf238,"Portamento On/Off");
  QString::QString((QString *)&DAT_140caf250,"Sostenuto On/Off");
  QString::QString((QString *)&DAT_140caf268,"Soft Pedal On/Off");
  QString::QString((QString *)&DAT_140caf280,"Legato Footswitch");
  QString::QString((QString *)&DAT_140caf298,"Hold 2");
  QString::QString((QString *)&DAT_140caf2b0,"Sound Variation");
  QString::QString((QString *)&DAT_140caf2c8,"Timbre");
  QString::QString((QString *)&DAT_140caf2e0,"Release Time");
  QString::QString((QString *)&DAT_140caf2f8,"Attack Time");
  QString::QString((QString *)&DAT_140caf310,"Brightness");
  QString::QString((QString *)&DAT_140caf328,"Decay Time");
  QString::QString((QString *)&DAT_140caf340,"Vibrato Rate");
  QString::QString((QString *)&DAT_140caf358,"Vibrato Depth");
  QString::QString((QString *)&DAT_140caf370,"Vibrato Delay");
  QString::QString((QString *)&DAT_140caf388,"Undefined");
  QString::QString((QString *)&DAT_140caf3a0,"General Purpose 5");
  QString::QString((QString *)&DAT_140caf3b8,"General Purpose 6");
  QString::QString((QString *)&DAT_140caf3d0,"General Purpose 7");
  QString::QString((QString *)&DAT_140caf3e8,"General Purpose 8");
  QString::QString((QString *)&DAT_140caf400,"Portamento Control");
  QString::QString((QString *)&DAT_140caf418,"Undefined");
  QString::QString((QString *)&DAT_140caf430,"Undefined");
  QString::QString((QString *)&DAT_140caf448,"Undefined");
  QString::QString((QString *)&DAT_140caf460,"High Res. Velocity");
  QString::QString((QString *)&DAT_140caf478,"Undefined");
  QString::QString((QString *)&DAT_140caf490,"Undefined");
  QString::QString((QString *)&DAT_140caf4a8,"Effect 1 Depth");
  QString::QString((QString *)&DAT_140caf4c0,"Effect 2 Depth");
  QString::QString((QString *)&DAT_140caf4d8,"Effect 3 Depth");
  QString::QString((QString *)&DAT_140caf4f0,"Effect 4 Depth");
  QString::QString((QString *)&DAT_140caf508,"Effect 5 Depth");
  QString::QString((QString *)&DAT_140caf520,"Data Increment");
  QString::QString((QString *)&DAT_140caf538,"Data Decrement");
  QString::QString((QString *)&DAT_140caf550,"NRPN LSB");
  QString::QString((QString *)&DAT_140caf568,"NRPN MSB");
  QString::QString((QString *)&DAT_140caf580,"RPN LSB");
  QString::QString((QString *)&DAT_140caf598,"RPN MSB");
  QString::QString((QString *)&DAT_140caf5b0,"Undefined");
  QString::QString((QString *)&DAT_140caf5c8,"Undefined");
  QString::QString((QString *)&DAT_140caf5e0,"Undefined");
  QString::QString((QString *)&DAT_140caf5f8,"Undefined");
  QString::QString((QString *)&DAT_140caf610,"Undefined");
  QString::QString((QString *)&DAT_140caf628,"Undefined");
  QString::QString((QString *)&DAT_140caf640,"Undefined");
  QString::QString((QString *)&DAT_140caf658,"Undefined");
  QString::QString((QString *)&DAT_140caf670,"Undefined");
  QString::QString((QString *)&DAT_140caf688,"Undefined");
  QString::QString((QString *)&DAT_140caf6a0,"Undefined");
  QString::QString((QString *)&DAT_140caf6b8,"Undefined");
  QString::QString((QString *)&DAT_140caf6d0,"Undefined");
  QString::QString((QString *)&DAT_140caf6e8,"Undefined");
  QString::QString((QString *)&DAT_140caf700,"Undefined");
  QString::QString((QString *)&DAT_140caf718,"Undefined");
  QString::QString((QString *)&DAT_140caf730,"Undefined");
  QString::QString((QString *)&DAT_140caf748,"Undefined");
  QString::QString((QString *)&DAT_140caf760,"All Sound Off");
  QString::QString((QString *)&DAT_140caf778,"Reset All Controllers");
  QString::QString((QString *)&DAT_140caf790,"Local Control On/Off");
  QString::QString((QString *)&DAT_140caf7a8,"All Notes Off");
  QString::QString((QString *)&DAT_140caf7c0,"Omni Mode Off");
  QString::QString((QString *)&DAT_140caf7d8,"Omni Mode On");
  QString::QString((QString *)&DAT_140caf7f0,"Mono Mode On");
  QString::QString((QString *)&DAT_140caf808,"Poly Mode On");
  atexit((_func_5014 *)&LAB_140050740);
  return;
}


